USE [master]
GO

/****** Object:  Database [CinemaDB]    Script Date: 4/8/2022 10:56:53 ******/
CREATE DATABASE [CinemaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CinemaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CinemaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CinemaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CinemaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CinemaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CinemaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CinemaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CinemaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CinemaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CinemaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CinemaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CinemaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CinemaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CinemaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CinemaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CinemaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CinemaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CinemaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CinemaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CinemaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CinemaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CinemaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CinemaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CinemaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CinemaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CinemaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CinemaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CinemaDB] SET RECOVERY FULL 
GO

ALTER DATABASE [CinemaDB] SET  MULTI_USER 
GO

ALTER DATABASE [CinemaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CinemaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CinemaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CinemaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CinemaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CinemaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CinemaDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CinemaDB] SET  READ_WRITE 
GO

